name: TOGA-mini
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - numpy
  - pandas
  - tqdm
  - jupyterlab
  - xgboost
  - scikit-learn
  - joblib
  - h5py
  - nextflow
  - bsddb3
  - cmake
  - make
  - gcc
  - pkg-config
  - pip
  - pip:
      - twobitreader
